<?php

use Drupal\mukurtu_media\Entity\Document;
use Drupal\mukurtu_media\Entity\Audio;
use Drupal\mukurtu_media\Entity\Image;
use Drupal\mukurtu_media\Entity\RemoteVideo;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function mukurtu_media_entity_bundle_info_alter(array &$bundles): void {
  if (isset($bundles['media']['document'])) {
    $bundles['media']['document']['class'] = Document::class;
  }
  if (isset($bundles['media']['audio'])) {
    $bundles['media']['audio']['class'] = Audio::class;
  }
  if (isset($bundles['media']['image'])) {
    $bundles['media']['image']['class'] = Image::class;
  }
  if (isset($bundles['media']['remote_video'])) {
    $bundles['media']['remote_video']['class'] = RemoteVideo::class;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function mukurtu_media_form_media_document_add_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // For new document forms, don't show the "Extracted Text" field because
  // no text has been extracted yet.
  if (isset($form['field_extracted_text'])) {
    $form['field_extracted_text']['#disabled'] = TRUE;
    $form['field_extracted_text']['#type'] = 'hidden';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function mukurtu_media_form_media_document_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // For existing document forms, make the "Extracted Text" field read only.
  if (isset($form['field_extracted_text'])) {
    $form['field_extracted_text']['#disabled'] = TRUE;
  }
}
