<?php

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\mukurtu_digital_heritage\Entity\DigitalHeritage;
use Drupal\mukurtu_digital_heritage\Entity\IndigenousKnowledgeKeepers;

/**
 * @file
 * Provide Mukurtu Digital Heritage Type.
 */

 /**
 * Implements hook_entity_bundle_info_alter().
 */
function mukurtu_digital_heritage_entity_bundle_info_alter(array &$bundles) {
  if (isset($bundles['node']['digital_heritage'])) {
    $bundles['node']['digital_heritage']['class'] = DigitalHeritage::class;
  }

  // Indigenous Knowledge Keepers Paragraph bundle class.
  if (isset($bundles['paragraph']['indigenous_knowledge_keepers'])) {
    $bundles['paragraph']['indigenous_knowledge_keepers']['class'] = IndigenousKnowledgeKeepers::class;
  }
}


/**
 * Implements hook_entity_field_storage_info().
 */
function mukurtu_digital_heritage_entity_field_storage_info(EntityTypeInterface $entity_type) {
  if ($entity_type->id() == 'paragraph') {
    return IndigenousKnowledgeKeepers::bundleFieldDefinitions($entity_type, 'indigenous_knowledge_keepers', []);
  }

  if ($entity_type->id() == 'node') {
    return DigitalHeritage::bundleFieldDefinitions($entity_type, 'digital_heritage', []);
  }
}


/**
 * Implements hook_form_form_id_alter().
 */
function mukurtu_digital_heritage_entity_bundle_info_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // Change digital heritage item title description
  $form['name']['widget'][0]['value']['#description'] = t('A short, descriptive name for the digital heritage item. The title should give users useful information about the item when browsing or searching. Titles do not have to be unique.');
}