<?php

// this attempts to address the extra field getting added on edit (it doesn't work tho)
function original_date_form_node_form_alter(&$form, &$form_state, $form_id)
{
  $field_name = 'field_original_date';
  // dpm($form[$field_name]);

  if (empty($form[$field_name])) {
    return;
  }

  $field_language = $form[$field_name]['#language'];
  $max_delta = $form[$field_name][$field_language]['#max_delta'];
  unset($form[$field_name][$field_language][$max_delta]);
}
