<?php

/**
 * Implements hook_migrate_destination_info_alter().
 */
function mukurtu_import_migrate_destination_info_alter(array &$definitions) {
  // Use the Mukurtu destination class for node and media.
  // This class handles protocol aware content.
  if (isset($definitions['entity:node'])) {
    $definitions['entity:node']['class'] = 'Drupal\mukurtu_import\Plugin\migrate\destination\ProtocolAwareEntityContent';
  }
  if (isset($definitions['entity:media'])) {
    $definitions['entity:media']['class'] = 'Drupal\mukurtu_import\Plugin\migrate\destination\ProtocolAwareEntityContent';
  }
  if (isset($definitions['entity:community'])) {
    $definitions['entity:community']['class'] = 'Drupal\mukurtu_import\Plugin\migrate\destination\ProtocolAwareEntityContent';
  }
  if (isset($definitions['entity:protocol'])) {
    $definitions['entity:protocol']['class'] = 'Drupal\mukurtu_import\Plugin\migrate\destination\ProtocolAwareEntityContent';
  }
}

/**
 * Implements hook_theme().
 */
function mukurtu_import_theme($existing, $type, $theme, $path) {
  return [
    'mukurtu_import_entity_bundle_list' => [
      'variables' => [
        'entity_types' => NULL,
        'entity_type_labels' => NULL,
        'entity_type_bundle_links' => NULL,
      ],
      'template' => 'mukurtu-import-entity-bundle-list',
      'base hook' => 'page',
    ],
  ];
}
