<?php

use Drupal\mukurtu_import\Plugin\migrate\destination\ProtocolAwareEntityContent;

/**
 * Implements hook_migrate_destination_info_alter().
 */
function mukurtu_import_migrate_destination_info_alter(array &$definitions) {
  // Use the Mukurtu destination class for node and media.
  // This class handles protocol aware content.
  if (isset($definitions['entity:node'])) {
    $definitions['entity:node']['class'] = ProtocolAwareEntityContent::class;
  }
  if (isset($definitions['entity:media'])) {
    $definitions['entity:media']['class'] = ProtocolAwareEntityContent::class;
  }
  if (isset($definitions['entity:community'])) {
    $definitions['entity:community']['class'] = ProtocolAwareEntityContent::class;
  }
  if (isset($definitions['entity:protocol'])) {
    $definitions['entity:protocol']['class'] = ProtocolAwareEntityContent::class;
  }
  if (isset($definitions['entity:multipage_item'])) {
    $definitions['entity:multipage_item']['class'] = ProtocolAwareEntityContent::class;
  }
  if (isset($definitions['entity:taxonomy_term'])) {
    $definitions['entity:taxonomy_term']['class'] = ProtocolAwareEntityContent::class;
  }
}

/**
 * Implements hook_views_data_alter().
 */
function mukurtu_import_views_data_alter(array &$data): void {
  $data['taxonomy_term_field_data']['mukurtu_import_term_status'] = [
    'title' => t('Import status'),
    'help' => t('Whether this term was newly created or updated during this import.'),
    'field' => [
      'id' => 'mukurtu_import_term_status',
    ],
  ];
}

/**
 * Implements hook_theme().
 */
function mukurtu_import_theme($existing, $type, $theme, $path) {
  return [
    'mukurtu_import_entity_bundle_list' => [
      'variables' => [
        'entity_types' => NULL,
        'entity_type_labels' => NULL,
        'entity_type_bundle_links' => NULL,
      ],
      'template' => 'mukurtu-import-entity-bundle-list',
      'base hook' => 'page',
    ],
  ];
}
