image: drupalpod/drupalpod-gitpod-base:latest
checkoutLocation: "mukurtu-cms"
workspaceLocation: "web"

# ddev and composer are running as part of the prebuild
# when starting a workspace all docker images are ready
tasks:
  - init: |
      cd /workspace
      ddev config --php-version 8.1 --project-type=drupal --docroot=web --create-docroot
      ddev start -y

      # These are not currently working. See #635.
      ddev exec wget https://dl.xpdfreader.com/xpdf-tools-linux-4.04.tar.gz
      ddev exec tar xzf xpdf-tools-linux-4.04.tar.gz
      ddev exec sudo cp xpdf-tools-linux-4.04/bin64/pdftotext /usr/local/bin/
      ddev exec rm -rf xpdf-tools-linux-4.04
      ddev exec rm xpdf-tools-linux-4.04.tar.gz

      ddev composer create mukurtu/mukurtu-template:dev-main . --no-install
      rm web/profiles/contrib/mukurtu-cms -rf
      # Add the git checkout as a local repository for composer.
      ddev composer config repositories.local-dev path mukurtu-cms
      # Symlink (instead of copying) it so that changes affect both places.
      ddev composer config repositories.local-package.options '{"symlink": true}'
      ddev composer install
      ddev drush site-install -y --account-pass=admin --site-name='Mukurtu CMS'
      echo "\$settings['file_private_path'] = './private_files';" | tee -a /workspace/web/sites/default/settings.php
      cp -R /workspace/web/profiles/mukurtu-cms/.vscode/ /workspace/web
      ddev xdebug on
    command: |
      ddev start -y
      gp ports await 8080 && gp preview $(gp url 8080)

# VScode xdebug extension
vscode:
  extensions:
    # PHP extensions.
    - felixfbecker.php-debug
    - wongjn.php-sniffer
    - neilbrayfield.php-docblocker
    - bmewburn.vscode-intelephense-client

    # Twig extensions.
    - mblode.twig-language-2

ports:
  # Used by ddev - local db clients
  - port: 3306
    onOpen: ignore
  # Used by projector
  - port: 6942
    onOpen: ignore
  # Used by MailHog
  - port: 8027
    onOpen: ignore
  # Used by phpMyAdmin
  - port: 8036
    onOpen: ignore
  # Direct-connect ddev-webserver port that is the main port
  - port: 8080
    onOpen: ignore
  # Ignore host https port
  - port: 8443
    onOpen: ignore
  # xdebug port
  - port: 9003
    onOpen: ignore
  # projector port
  - port: 9999
    onOpen: open-browser
