entity_browser.browser.widget.mukurtu_user_selection:
  type: mapping
  label: 'View widget configuration'
  mapping:
    submit_text:
      type: label
      label: 'Submit button text'

entity_browser.browser.widget.mukurtu_taxonomy_record_term_selection:
  type: mapping
  label: 'View widget configuration'
  mapping:
    submit_text:
      type: label
      label: 'Submit button text'

mukurtu_protocol.comment_settings:
  type: config_object
  label: 'Mukurtu Comment Settings'
  mapping:
    site_comments_enabled:
      type: integer

field.field_settings.cultural_protocol:
  type: mapping
  label: 'Cultural Protocol settings'
  mapping:
    target_id:
      type: integer
      label: 'Protocol Control ID'
