<?php

/**
 *  Implements hook_theme().
 */
function mukurtu_local_contexts_theme($existing, $type, $theme, $path) {
  return [
    'local_contexts_project' => [
      'template' => 'local-contexts-project',
      'variables' => [
        'title' => [],
        'privacy' => [],
        'tk_labels' => [],
        'bc_labels' => [],
        'notices' => [],
      ],
    ],
    'local_contexts_label' => [
      'template' => 'local-contexts-label',
      'variables' => [
        'text' => [],
        'name' => [],
        'svg_url' => [],
        'translations' => [],
      ],
    ],
    'local_contexts_notice' => [
      'template' => 'local-contexts-notice',
      'variables' => [
        'text' => [],
        'name' => [],
        'svg_url' => [],
        'translations' => [],
      ],
    ],
  ];
}
