<?php

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\StringTranslation\TranslatableMarkup;

/**
 *  Implements hook_theme().
 */
function mukurtu_local_contexts_theme($existing, $type, $theme, $path) {
  return [
    'local_contexts_project' => [
      'template' => 'local-contexts-project',
      'variables' => [
        'title' => [],
        'privacy' => [],
        'labels' => [],
        'notices' => [],
      ],
    ],
    'local_contexts_labels_and_notices' => [
      'template' => 'local-contexts-label-and-notice',
      'variables' => [
        'text' => [],
        'name' => [],
        'svg_url' => [],
        'translations' => [],
      ],
    ],
  ];
}

function mukurtu_local_contexts_entity_bundle_field_info(EntityTypeInterface $entity_type, $bundle, array $base_field_definitions) {
  if ($entity_type->id() == 'user' && $bundle == 'user') {
    $fields = [];
    $fields['field_local_contexts_user_id'] = BaseFieldDefinition::create('integer')
      ->setLabel(new TranslatableMarkup("Local Contexts Hub User ID"))
      ->setDescription(new TranslatableMarkup("The Local Contexts Hub User ID to use for this user."))
      ->setDisplayConfigurable('form', TRUE);
    return $fields;
  }
}
