mukurtu.settings:
  type: config_object
  label: 'Mukurtu settings'
  mapping:
    mukurtu_media_download_enabled:
      type: boolean
      label: 'Enable media download button'

mukurtu_thumbnail.settings:
  type: config_object
  label: 'Mukurtu Thumbnail Settings'
  mapping:
    default_thumbnail:
      type: sequence
      label: 'Default thumbnails for media bundles.'
      sequence:
        type: string
        label: 'Thumbnail fid.'
