mukurtu_thumbnail.settings:
  type: config_object
  label: 'Mukurtu Thumbnail Settings'
  mapping:
    default_thumbnail:
      type: sequence
      label: 'Default thumbnails for media bundles.'
      sequence:
        type: string
        label: 'Thumbnail fid.'
