<?php

/**
 * Implements hook_theme().
 */
function mukurtu_footer_theme($existing, $type, $theme, $path) {
  return [
    'mukurtu_footer' => [
      'template' => 'mukurtu-footer',
      'variables' => [
        'logos' => [],
        'logo_alt' => [],
        'email_us_text' => [],
        'contact_email_address' => [],
        'twitter' => [],
        'twitter_accounts' => [],
        'facebook' => [],
        'facebook_accounts' => [],
        'instagram' => [],
        'instagram_accounts' => [],
        'copyright_message' => [],
      ],
    ],
  ];
}
