<?php

/**
 * Implements hook_theme().
 */
function mukurtu_footer_theme($existing, $type, $theme, $path) {
  return [
    'mukurtu_footer' => [
      'template'  => 'mukurtu-footer',
      'variables' => [
        'text_field'            => [],
        'logos'                 => [],
        'social_accounts'       => [],
        'other_links'           => [],
        'contact_email_text'    => '',
        'contact_email_address' => '',
        'copyright_message'     => '',
      ],
    ],
  ];
}
