blank_issues_enabled: true
contact_links:
  - name: Mukurtu Support
    url: https://support.mukurtu.org
    about: The user story forms are for feature requests and technical bug reports. If you need support, please review our documentation and contact the support team here.