name: Mukurtu CMS User Stories Submission - General Users
description: Use this form if you are submitting an issue as a general Mukurtu user.
title: Mukurtu CMS User Stories Submission - General Users 
labels: "user story"
body:
  - type: checkboxes
    id: story_type
    attributes:
      label: Type of user story
      description: Select the type of user story.
      options:
        - label: New feature/tool
        - label: Update to existing feature/tool
        - label: Other
    validations:
       required: true

  - type: input
    id: story_type_other
    attributes: 
      label: Other
      description: If you selected "Other", please briefly describe your story type.
    validations:
      required: false

  - type: checkboxes
    id: story_topic
    attributes:
      label: Topic of user story
      description: From the [Mukurtu User Manual](https://mukurtu-user-manual.readthedocs.io/). Can select multiple topics. Specify other if existing topics do not apply.
      options:
        - label: bug
        - label: categories
        - label: collections
        - label: comments
        - label: communities
        - label: cultural protocols
        - label: customization
        - label: dictionary
        - label: digital heritage
        - label: integrations
        - label: local contexts
        - label: localization
        - label: mapping and leaflet
        - label: media
        - label: migration
        - label: notifications/events
        - label: person records
        - label: roundtrip
        - label: search and discovery
        - label: site configuration and administration
        - label: taxonomies
        - label: theme/look and feel
        - label: user management
    validations:
      required: true

  - type: input
    id: story_topic_other
    attributes: 
      label: Other topics
      description: If you selected "Other topics", please briefly describe your story topic.
    validations:
      required: false

  - type: checkboxes
    id: user_type
    attributes:
      label: In this user role
      description: Select each user type that this applies to. Can select multiple user types. 
      options:
        - label: Mukurtu administrator
        - label: Community manager
        - label: Community affiliate
        - label: Protocol steward
        - label: Protocol member
        - label: Protocol affiliate
        - label: Contributor
        - label: Community record steward
        - label: Curator
        - label: Language steward
        - label: Lanugage contributor
        - label: Authenticated user
        - label: Visitor
    validations:
      required: true

  - type: input
    id: Action
    attributes:
      label: I want to perform this action
      description: Please describe the action you would like to take in this role.
    validations:
      required: true

  - type: input
    id: Benefit
    attributes:
      label: So that this benefit will occur. 
      description: Please describe the benefit that taking this action would confer.
    validations:
      required: true

  - type: input
    id: Acceptance_criteria
    attributes:
      label: Acceptance criteria
      description: A list of items or descriptions of what success looks like for the action or feature described. For a list, please number or bullet your points.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Example screenshots
      description: Optionally attach screenshots here.
      placeholder: If you have an example of something similar from elsewhere, you can add screenshots here. 
  - type: input
    id: submitting_org
    attributes: 
      label: Organization
      description: Identify your institution, organization, or community.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        Support Tools: 
        - [Mukurtu 4 User Manual](https://mukurtu-user-manual.readthedocs.io/)
