<?php

/**
 * @file
 * Contains hook implementations for the Search API Views Test module.
 */

use Drupal\Component\Render\FormattableMarkup;
use Drupal\Core\Cache\RefinableCacheableDependencyInterface;
use Drupal\Core\Database\Query\SelectInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityListBuilder;
use Drupal\search_api\Query\QueryInterface;
use Drupal\search_api\SearchApiException;

/**
 * Implements hook_search_api_query_alter().
 *
 * - Prints the contents of the "search_api_retrieved_field_values" query option
 *   to the page (if present) so it can be checked by the testing code.
 * - Optionally alters the query to include custom cacheability metadata, so
 *   that we can test if modules can alter the cacheability of search queries.
 */
function search_api_test_views_search_api_query_alter(QueryInterface $query) {
  $fields = $query->getOption('search_api_retrieved_field_values');
  if ($fields) {
    \Drupal::messenger()->addStatus("'" . implode("' '", $fields) . "'");
  }

  $alter_cache_metadata = \Drupal::state()
    ->get('search_api_test_views.alter_query_cacheability_metadata', FALSE);

  if ($alter_cache_metadata
      && $query instanceof RefinableCacheableDependencyInterface) {
    // Alter in some imaginary cacheability metadata for testing, including a
    // cache tag that depends on the search ID (to simulate caching information
    // that depends on the specific search).
    $query->addCacheContexts(['views_test_cache_context']);
    $query->addCacheTags([
      'search_api:test_tag',
      'search_api:test_' . $query->getSearchId(),
    ]);
    $query->mergeCacheMaxAge(100);
  }

}

/**
 * Implements hook_entity_type_alter().
 */
function search_api_test_views_entity_type_alter(array &$entity_types) {
  // We need list builder for entity type in order to test operations column.
  if (!empty($entity_types['entity_test_mulrev_changed'])) {
    $entity_types['entity_test_mulrev_changed']
      ->setListBuilderClass(EntityListBuilder::class);
  }
}

/**
 * Implements hook_entity_operation().
 */
function search_api_test_views_entity_operation(EntityInterface $entity) {
  if ($entity->getEntityTypeId() !== 'entity_test_mulrev_changed') {
    return [];
  }

  // For testing purpose we want to have one entity without operations.
  if ($entity->id() == 2) {
    return [];
  }

  $operations['edit'] = [
    'title' => t('Edit'),
    'url' => $entity->toUrl('edit-form'),
    'weight' => 0,
  ];
  $operations['delete'] = [
    'title' => t('Delete'),
    'url' => $entity->toUrl('delete-form'),
    'weight' => 1,
  ];

  return $operations;
}

/**
 * Implements hook_ENTITY_TYPE_view_alter() for entity type "node".
 *
 * If the "search_api_test_views.testViewsBlockRenderedInCurrentRequest" state
 * key is set to TRUE, this will display the return value of the
 * isRenderedInCurrentRequest() method of the test view search block display on
 * the page.
 *
 * @see \Drupal\Tests\search_api\Functional\LayoutBuilderTest::testViewsBlockRenderedInCurrentRequest()
 */
function search_api_test_views_node_view_alter(array &$build) {
  $enabled = \Drupal::state()
    ->get('search_api_test_views.testViewsBlockRenderedInCurrentRequest');
  if (!$enabled) {
    return;
  }
  /** @var \Drupal\search_api\Display\DisplayInterface $display */
  $display = \Drupal::getContainer()->get('plugin.manager.search_api.display')
    ->createInstance('views_block:search_api_test_view__block_1');
  $result = $display->isRenderedInCurrentRequest();
  $string = 'views_block:search_api_test_view__block_1.isRenderedInCurrentRequest(): @result';
  $build['search_api_test_views']['#markup'] = new FormattableMarkup($string, [
    '@result' => $result ? 'TRUE' : 'FALSE',
  ]);
}

/**
 * Implements hook_search_api_db_query_alter().
 *
 * Throws an exception when the search is executed if the
 * "search_api_test_views.throw_exception" state key is set.
 */
function search_api_test_views_search_api_db_query_alter(SelectInterface &$db_query, QueryInterface $query) {
  $throw_exception = \Drupal::keyValue('search_api_test_views')
    ->get('throw_exception', FALSE);
  if ($throw_exception) {
    if ($query instanceof RefinableCacheableDependencyInterface) {
      $query->mergeCacheMaxAge(0);
    }
    throw new SearchApiException('Test exception thrown from search_api_test_views_search_api_query_alter().');
  }
}
