<?php

/**
 * @file
 * Test fixtures for PrunesEmptyParagraphsTrait.
 */

use Drupal\mukurtu_core_paragraph_prune_test\Entity\PruneTestContent;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function mukurtu_core_paragraph_prune_test_entity_bundle_info_alter(array &$bundles) {
  if (isset($bundles['node']['prune_test_content'])) {
    $bundles['node']['prune_test_content']['class'] = PruneTestContent::class;
  }
}
