<?php

/**
 * @file
 * Install, update and uninstall functions for the mukurtu_collection module.
 */

/**
 * Update the weight of field_coverage in the collection form display.
 */
function mukurtu_collection_update_8001() {
  $config = \Drupal::configFactory()->getEditable('core.entity_form_display.node.collection.default');
  $config->set('content.field_coverage.weight', 0);
  $config->save();
  return t('Updated the weight of field_coverage in collection form display.');
}
