<?php

/**
 * @file
 * Provides a multipage item entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function mukurtu_multipage_items_theme() {
  return [
    'multipage_item' => [
      'render element' => 'elements',
    ],
    'multipage_item_book_view' => [
      'variables' => [
        'pages' => [],
        'page_nav_attributes' => NULL,
        'current_page' => NULL,
        'current_page_attributes' => NULL,
/*         'next_page' => NULL,
        'previous_page' => NULL, */
      ],
    ],
  ];
}

/**
 * Prepares variables for multipage item templates.
 *
 * Default template: multipage-item.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the multipage item information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_multipage_item(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
