mukurtu_site_settings.design_settings:
  title: 'Design settings'
  route_name: mukurtu_design.settings
  description: 'Set the color palette and background images.'
  parent: mukurtu_dashboard
  menu_name: dashboard-look-feel
  weight: 2
