name: Mukurtu Site Settings
type: module
description: Contains hooks for the Site Settings config pages.
package: Custom
core_version_requirement: '^9.4 || ^10 || ^11'
dependencies:
  - drupal:config_pages
  - mukurtu_design
