<?php

/**
 * @file
 * Geolocation demo setup.
 */

/**
 * Implements hook_install().
 */
function geolocation_google_maps_test_install() {
  /** @var \Drupal\Core\Config\Config $config */
  $config = \Drupal::service('config.factory')->getEditable('geolocation_google_maps.settings');
  if (empty($config->get('google_map_api_key'))) {
    $config->set('google_map_api_key', 'AIzaSyBTq76GbylL-gnN9oHu4XV6se_N3h0YpWg')->save();
  }
}

/**
 * Implements hook_uninstall().
 */
function geolocation_google_maps_test_uninstall() {
  /** @var \Drupal\Core\Config\Config $config */
  $config = \Drupal::service('config.factory')->getEditable('geolocation_google_maps.settings');
  if ($config->get('google_map_api_key') == 'AIzaSyBTq76GbylL-gnN9oHu4XV6se_N3h0YpWg') {
    $config->set('google_map_api_key', '')->save();
  }
}
