<?php

/**
 * @file
 * Provide Mukurtu Taxonomies.
 */

use Drupal\Core\Url;
use Drupal\Core\Link;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Access\AccessResult;
use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;

/**
 * Implements hook_theme().
 */
function mukurtu_taxonomy_theme($existing, $type, $theme, $path) {
  return [
    'mukurtu_vocabulary_add_list' => [
      'template' => 'mukurtu-vocabulary-add-list',
      'variables' => ['content' => NULL],
    ],
    'taxonomy_records' => [
      'template' => 'taxonomy-records',
      'variables' => [
        'active' => NULL,
        'records' => NULL,
        'referenced_content' => NULL,
        'facets' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_entity_access().
 */
function mukurtu_taxonomy_entity_access(EntityInterface $entity, $operation, AccountInterface $account) {
  if ($entity->getEntityTypeId() === 'taxonomy_vocabulary') {
    $vocabs = [
      'authors',
      'category',
      'community_type',
      'contributor',
      'creator',
      'format',
      'interpersonal_relationship',
      'keywords',
      'language',
      'location',
      'media_tag',
      'people',
      'publisher',
      'subject',
      'type',
      'word_type',
    ];
    if ($operation === 'delete' && in_array($entity->id(), $vocabs)) {
      // Don't allow the any of our Mukurtu taxonomy vocabs to be deleted.
      return AccessResult::forbidden();
    }
  }
}

/**
 * Implements hook_form_form_id_alter().
 */
function mukurtu_taxonomy_form_taxonomy_term_category_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // Change Category title field label.
  $form['name']['widget'][0]['value']['#title'] = t('Category name');
}

/**
 * Implements hook_form_form_id_alter().
 *
 * Change the description of the 'Terms to merge' form element for the
 * taxonomy_merge_terms form:
 * (admin/structure/taxonomy/manage/{taxonomy_vocabulary}/merge).
 */
function mukurtu_taxonomy_form_taxonomy_merge_terms_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $form['terms']['#description'] = t('To merge multiple terms into a new target term, select all terms to merge here. The new target term will be created on the next page.</>To merge one or more terms into another existing target term, select them here. The target term will be selected on the next page, do not select it now.');
  $form['actions']['submit']['#value'] = t('Next');
}

function mukurtu_taxonomy_form_taxonomy_merge_terms_target_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $form['description']['#markup'] = t('To merge the selected terms into a new target term, enter it in the "New term" field.<br/>To merge the selected term(s) into an existing target term, select it from the "Existing term" list.');
  $form['actions']['submit']['#value'] = t('Merge terms');
}

/**
 * Prepares variables for list of available vocabulary templates.
 *
 * Default template: mukurtu-vocabulary-add-list.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - content: An array of content types.
 */
function template_preprocess_mukurtu_vocabulary_add_list(array &$variables) {
  $variables['types'] = [];

  if (!empty($variables['content'])) {
    foreach ($variables['content'] as $type) {
      $variables['types'][$type->id()] = [
        'type' => $type->id(),
        'add_link' => Link::fromTextAndUrl($type->label(), Url::fromRoute('mukurtu_taxonomy.manage_taxonomy_vocabulary', ['taxonomy_vocabulary' => $type->id()]))->toString(),
        'description' => [
          '#markup' => $type->getDescription(),
        ],
      ];
    }
  }
}


/**
 * Implements hook_views_pre_view().
 */
function mukurtu_taxonomy_views_pre_view(ViewExecutable $view) {
  // This drives the handling of the taxonomy term page view.
  // It injects the UUID of the term into the fulltext SAPI search.
  if (strpos($view->id(),'mukurtu_taxonomy_references') !== FALSE) {
    if ($term = \Drupal::routeMatch()->getParameter('taxonomy_term')) {
      $filters = $view->display_handler->getOption('filters');
      $filters['search_api_fulltext']['value'] = $term->uuid();
      $view->display_handler->overrideOption('filters', $filters);
    }
  }
}

