<?php

/**
 * @file
 * Install, update and uninstall functions for the mukurtu_community_records module.
 */

/**
 * Implements hook_install().
 */
function mukurtu_community_records_install() {
  // Create the community records field on all pre-existing node types.
/*   foreach (node_type_get_names() as $bundle => $label) {
    mukurtu_community_records_create_community_records_field('node', $bundle);
  } */
}
