services:
  php:
    # See: https://github.com/TugboatQA/dockerfiles/blob/main/php/TAGS.md
    image: tugboatqa/php:8.3-apache
    default: true
    depends: mariadb
    commands:
      init:
        # Install dependencies for PHP extensions.
        - apt update && apt install -y libzip-dev libpng-dev libjpeg-dev libfreetype6-dev

        # Add JPEG and FreeType support to GD.
        - docker-php-ext-configure gd --with-jpeg --with-freetype

        # Install the PHP extensions all at once to minimize rebuilding.
        - docker-php-ext-install zip opcache gd

        # Enable Apache 'rewrite' module for clean URLs.
        - a2enmod rewrite

        # Adjust a few PHP settings. Higher memory limit is needed for install.
        - echo "upload_max_filesize=100M" >> /usr/local/etc/php/conf.d/tugboat.ini
        - echo "post_max_size=100M" >> /usr/local/etc/php/conf.d/tugboat.ini
        - echo "memory_limit=512M" >> /usr/local/etc/php/conf.d/tugboat.ini

        # Install composer.
        # See https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md
        - wget https://raw.githubusercontent.com/composer/getcomposer.org/main/web/installer -O - -q | php -- --quiet
        - mv composer.phar /usr/local/bin/composer

        # Make a directory in which the Mukurtu template will be installed.
        - |
          # The home directory needs to be readable by www-data.
          chmod 755 ~
          mkdir ~/mukurtu
          cd ~/mukurtu
          # @todo Replace with composer create-project. See #610.
          wget https://raw.githubusercontent.com/MukurtuCMS/Mukurtu-CMS-v4-Project-Template/main/composer.json
          # Remove the VCS-based repository.
          composer config --unset repositories.5
          # Add our own local checkout repository instead. This will use the
          # local directory as the source, copying it into the final location.
          composer config repositories.local-mukurtu path $TUGBOAT_ROOT
          composer install --no-ansi --no-interaction --optimize-autoloader --no-progress

        # Symlink the web root and grant read access to the home directory.
        - ln -snf ~/mukurtu/web $DOCROOT

      update:
        # Set appropriate file permissions/ownership for the files directory.
        - |
          cd ~/mukurtu/web
          mkdir -p sites/default/files
          chown -R www-data:www-data sites/default/files
          find sites/default/files -type d -exec chmod 2775 {} \;
          find sites/default/files -type f -exec chmod 0664 {} \;
      build:
        - |
          cd ~/mukurtu
          # Copy in the settings.php file to set the database connection.
          cp $TUGBOAT_ROOT/.tugboat/settings.tugboat.php web/sites/default/settings.php
          # Update composer dependencies.
          composer update --no-ansi --no-interaction --optimize-autoloader --no-progress
          # Install Drupal with the Mukurtu installation profile.
          ./vendor/bin/drush site-install mukurtu -y --account-pass="admin" --site-name="Mukurtu CMS"
  mariadb:
    image: tugboatqa/mariadb:lts
    commands:
      init:
        # Increase the allowed packet size to 512MB.
        - mariadb -e "SET GLOBAL max_allowed_packet=536870912;"
        # Ensure this packet size persists even if MySQL restarts.
        - echo "max_allowed_packet=536870912" >> /etc/mysql/conf.d/tugboat.cnf
      build:
        # Drop and re-create the database (needed when rebuilding/reinstalling).
        - mariadb-admin -f drop tugboat && mariadb-admin create tugboat
