mukurtu_multipage_items.settings:
  type: config_object
  label: 'Mukurtu Multipage Items Settings'
  mapping:
    bundles_config:
      type: sequence
      label: 'Bundles enabled for multipage'
      sequence:
        type: boolean
        label: 'Bundle Enabled Status'
    _controller:
      type: string
      label: 'Original controller'
