<?php

/**
 * @file
 * Yandex Maps hooks.
 */

use Drupal\Core\Asset\AttachedAssetsInterface;

/**
 * Implements hook_library_info_build().
 */
function geolocation_yandex_library_info_build() {
  /** @var \Drupal\geolocation_yandex\Plugin\geolocation\MapProvider\Yandex $yandex */
  $yandex = Drupal::service('plugin.manager.geolocation.mapprovider')->getMapProvider('yandex');

  $libraries = [];
  $libraries['yandex_maps'] = [
    'version' => '1.x',
    'js' => [
      $yandex->getApiUrl() => [
        'type' => 'external',
      ],
    ],
  ];

  return $libraries;
}

/**
 * Implements hook_js_alter().
 */
function geolocation_yandex_js_alter(&$javascript, AttachedAssetsInterface $assets) {
  if (!Drupal::moduleHandler()->moduleExists('language')) {
    return;
  }

  /** @var \Drupal\geolocation_yandex\Plugin\geolocation\MapProvider\Yandex $yandex */
  $yandex = Drupal::service('plugin.manager.geolocation.mapprovider')->getMapProvider('yandex');

  foreach ($javascript as $key => $js) {
    if (strpos($key, $yandex::$apiBaseUrl) === 0 && strpos($key, 'lang=') > 0) {
      $javascript[$key]['data'] = $yandex->getApiUrl();
    }
  }
}
