<?php

/**
 * @file
 * Provides UI and implements hook to force taxonomies to be flat.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\flat_taxonomy\FlatConstants;
use Drupal\taxonomy\Entity\Term;
use Drupal\taxonomy\Entity\Vocabulary;
use Drupal\taxonomy\TermInterface;

/**
 * Implements hook_requirements().
 */
function flat_taxonomy_requirements($phase) {
  if ($phase !== 'runtime') {
    return [];
  }

  $requirements = [];

  $enabled_modules = \Drupal::moduleHandler()->getModuleList();
  if (isset($enabled_modules['hierarchy_manager'])) {

    $hm_vocabularies = [];
    $allowed_setup_plugins = \Drupal::config('hierarchy_manager.hmconfig')->get('allowed_setup_plugins');
    if (isset($allowed_setup_plugins['hm_setup_taxonomy']) && $allowed_setup_plugins['hm_setup_taxonomy']) {
      $setup_plugin_settings = \Drupal::config('hierarchy_manager.hmconfig')->get('setup_plugin_settings');
      if (isset($setup_plugin_settings['hm_setup_taxonomy'])) {
        $hm_vocabularies = array_keys(array_filter($setup_plugin_settings['hm_setup_taxonomy']['bundle']));
      }
    }

    $ft_vocabularies = [];
    foreach (Vocabulary::loadMultiple() as $vocabulary) {
      if ($vocabulary->getThirdPartySetting('flat_taxonomy', 'flat')) {
        $ft_vocabularies[] = $vocabulary->id();
      }
    }

    if (!empty(array_intersect($hm_vocabularies, $ft_vocabularies))) {
      $requirements['flat_taxonomy'] = [
        'title' => t('Flat taxonomy incompatibility'),
        'value' => t('Flat taxonomy and Hierarchy Manager are enabled on same taxonomies.'),
        'description' => t('Flat taxonomy and Hierarchy Manager modules both alter the following taxonomies: %vocabularies, which can lead to inconsistent behaviours.', ['%vocabularies' => implode(',', array_intersect($ft_vocabularies, $hm_vocabularies))]),
        'severity' => REQUIREMENT_WARNING,
      ];
    }
  }

  return $requirements;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function flat_taxonomy_form_taxonomy_vocabulary_form_alter(array &$form, FormStateInterface $form_state): void {
  $vocabulary = $form_state->getFormObject()->getEntity();

  $form['flat'] = [
    '#type' => 'checkbox',
    '#title' => t('Flat taxonomy'),
    '#description' => t("If checked, the taxonomy will be flat, terms can be ordered but can't be nested"),
    '#default_value' => $vocabulary->getThirdPartySetting('flat_taxonomy', 'flat'),
  ];

  $form['#entity_builders'][] = 'flat_taxonomy_form_taxonomy_vocabulary_form_builder';

  // @todo Add a confirm step if the vocabulary is updated to be flatten and
  // already has terms (see 7.x version of the module).
}

/**
 * Entity form builder to add the flat information to the vocabulary.
 *
 * @see flat_taxonomy_form_taxonomy_vocabulary_form_alter()
 */
function flat_taxonomy_form_taxonomy_vocabulary_form_builder(string $entity_type, Vocabulary $vocabulary, array &$form, FormStateInterface $form_state): void {
  if ($form_state->getValue('flat')) {
    $vocabulary->setThirdPartySetting('flat_taxonomy', 'flat', $form_state->getValue('flat'));
    \Drupal::service('flat_taxonomy.taxonomy_flattener')->flatten($vocabulary);
    return;
  }

  $vocabulary->unsetThirdPartySetting('flat_taxonomy', 'flat');
}

/**
 * Implements hook_taxonomy_term_presave().
 */
function flat_taxonomy_taxonomy_term_presave(Term $term): void {
  // If the term is nested but is part of a flat taxonomy, we update the
  // parent and log the change. This is not supposed to occur via the normal
  // edit form as the parent field is hidden but it may occur via a
  // programmatical save (migration, services, ...).
  $vocabulary = Vocabulary::load($term->bundle());

  if (
    $vocabulary->getThirdPartySetting('flat_taxonomy', 'flat') == FlatConstants::FLAT_TAXONOMY_FLAT
    && !empty($term->parent->target_id)
  ) {
    \Drupal::logger('flat_taxonomy')->warning('Illegal parent %parent_tid for the term %name as vocabulary is flat. Parent has been updated.', [
      '%parent_tid' => $term->parent->target_id,
      '%name' => $term->name->value,
    ]);
    \Drupal::messenger()->addMessage(t('Illegal parent %parent_tid for the term %name as vocabulary is flat. Parent has been updated.', [
      '%parent_tid' => $term->parent->target_id,
      '%name' => $term->name->value,
    ]), 'warning');

    // @todo Update the term weight so it is ordered after the parent.
    $term->parent = 0;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function flat_taxonomy_form_taxonomy_term_form_alter(&$form, FormStateInterface $form_state): void {
  if ($form_state->getStorage()['taxonomy']['vocabulary']->getThirdPartySetting('flat_taxonomy', 'flat') == FlatConstants::FLAT_TAXONOMY_FLAT) {
    $form['relations']['parent']['#access'] = FALSE;

    $form['#validate'][] = 'flat_taxonomy_form_taxonomy_form_term_validate';
  }
}

/**
 * Custom validate handler for the taxonomy term add/edit form.
 */
function flat_taxonomy_form_taxonomy_form_term_validate($form, FormStateInterface &$form_state): void {
  if ($form_state->getValue('parent')[0]) {
    $form_state->setErrorByName('parent', t("This term can't have any parent as it is part of a flat taxonomy."));
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function flat_taxonomy_form_taxonomy_overview_terms_alter(&$form, FormStateInterface $form_state): void {
  $vocabulary = $form_state->getStorage()['taxonomy']['vocabulary'] ?? NULL;

  if ($vocabulary && $form_state->getStorage()['taxonomy']['vocabulary']->getThirdPartySetting('flat_taxonomy', 'flat') === FlatConstants::FLAT_TAXONOMY_FLAT
    && !empty($form['terms']['#tabledrag'])) {
    $form['help']['message']['#markup'] = t('You can reorder the terms in %capital_name using their drag-and-drop handles.', $form['help']['message']['#markup']->getArguments());
    foreach ($form['terms']['#tabledrag'] as $index => $data) {
      if (isset($data['group']) && ($data['group'] == 'term-depth' || $data['group'] == 'term-parent')) {
        unset($form['terms']['#tabledrag'][$index]);
      }
    }
  }
}

/**
 * Implements hook_entity_operation_alter().
 */
function flat_taxonomy_entity_operation_alter(array &$operations, EntityInterface $entity) {
  if (!$entity instanceof TermInterface || !array_key_exists('add-child', $operations)) {
    return;
  }
  $vocabulary = Vocabulary::load($entity->bundle());
  if ($vocabulary->getThirdPartySetting('flat_taxonomy', 'flat') != FlatConstants::FLAT_TAXONOMY_FLAT) {
    return;
  }
  unset($operations['add-child']);
}

/**
 * Implements hook_help().
 */
function flat_taxonomy_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.flat_taxonomy':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Flat Taxonomy provides a new option on vocabulary creation or edit to enforce the vocabulary to be "flat"— non-hierarchical, with no terms nested under other terms.') . '</p>';
      $output .= '<p>' . t('This module therefore avoids the situation where a site is built with the assumption that a vocabulary is supposed to be flat, but later a content editor makes a term with the parent field set to another term, making it a hierarchical vocabulary, which may cause errors or unexpected behavior on the front end or back end.') .'</p>';
      $output .= '<p>' . t('Specifically, this module:') . '</p>';
      $output .= '<ul><li>' . t('Alters the term creation/edit form to make it impossible to select a parent.') . '</li>';
      $output .= '<li>' . t('Removes the "Add child" operation link from the vocabulary overview taxonomy term listing.') . '</li>';
      $output .= '<li>'.t('Alters the vocabulary overview term listing page to make it impossible to create a nested vocabulary through drag and drop.') . '</li></ul>';
      return $output;
  }
}
