block.settings.mukurtu_core_example:
  type: block_settings
  label: 'Example block'
  mapping:
    foo:
      type: string
      label: Foo

media.source.external_embed:
  type: media.source.field_aware
  label: '"External Embed" media source configuration'
