<?php

/**
 * @file
 * Install, update and uninstall functions for the mukurtu_community module.
 */

use Drupal\og\Og;

/**
 * Implements hook_install().
 */
function mukurtu_community_install() {
  // Communities are groups.
  Og::addGroup('node', 'community');

  // Create the community field on all pre-existing node types.
  foreach (node_type_get_names() as $bundle => $label) {
    mukurtu_community_create_community_field('node', $bundle);
  }
}
