<?php

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Field\FieldStorageDefinitionInterface;
use Drupal\mukurtu_dictionary\Entity\DictionaryWord;
use Drupal\mukurtu_dictionary\Entity\DictionaryWordEntry;
use Drupal\mukurtu_dictionary\Entity\SampleSentence;
use Drupal\mukurtu_dictionary\Entity\WordList;

/**
 * Implements hook_theme().
 */
function mukurtu_dictionary_theme($existing, $type, $theme, $path) {
  return [
    'mukurtu_dictionary_page' => [
      'variables' => [
        'results' => NULL,
        'facets' => [],
        'glossary' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_entity_bundle_info_alter().
 */
function mukurtu_dictionary_entity_bundle_info_alter(array &$bundles): void {
  // Dictionary word bundle class.
  if (isset($bundles['node']['dictionary_word'])) {
    $bundles['node']['dictionary_word']['class'] = DictionaryWord::class;
  }

  // Word list bundle class.
  if (isset($bundles['node']['word_list'])) {
    $bundles['node']['word_list']['class'] = WordList::class;
  }

  // Dictionary Word Entry bundle class.
  if (isset($bundles['paragraph']['dictionary_word_entry'])) {
    $bundles['paragraph']['dictionary_word_entry']['class'] = DictionaryWordEntry::class;
  }

  // Sample sentences bundle class.
  if (isset($bundles['paragraph']['sample_sentence'])) {
    $bundles['paragraph']['sample_sentence']['class'] = SampleSentence::class;
  }
}

/**
 * Implements hook_entity_access().
 */
function mukurtu_dictionary_entity_access(EntityInterface $entity, $operation, AccountInterface $account) {
  if ($entity->getEntityTypeId() === 'paragraphs_type') {
    if($entity->id() === 'dictionary_word_entry' && $operation === 'delete') {
      // Don't allow the dictionary word entry paragraph type to be deleted.
      return AccessResult::forbidden();
    }
  }
}

/**
 * Implements hook_entity_bundle_field_info().
 */
function mukurtu_dictionary_entity_bundle_field_info(EntityTypeInterface $entity_type, $bundle, array $base_field_definitions) {
  if ($entity_type->id() == 'node' && $bundle == 'dictionary_word') {
    $fields = [];
    $fields['field_in_word_list'] = BaseFieldDefinition::create('entity_reference')
      ->setName('field_in_word_list')
      ->setLabel(t('Word Lists'))
      ->setDescription(t('Word lists this word is contained in.'))
      ->setComputed(TRUE)
      ->setClass('Drupal\mukurtu_dictionary\Plugin\Field\MukurtuInWordListFieldItemsList')
      ->setTargetEntityTypeId('node')
      ->setTargetBundle('word_list')
      ->setRevisionable(FALSE)
      ->setTranslatable(FALSE)
      ->setCardinality(FieldStorageDefinitionInterface::CARDINALITY_UNLIMITED)
      ->setDisplayConfigurable('view', TRUE);

    return $fields;
  }
}
