<?php

use Drupal\mukurtu_dictionary\Entity\DictionaryWord;

/**
 * Implements hook_theme().
 */
function mukurtu_dictionary_theme($existing, $type, $theme, $path) {
  return [
    'mukurtu_dictionary_page' => [
      'variables' => [
        'results' => NULL,
        'facets' => [],
        'glossary' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_entity_bundle_info_alter().
 */
function mukurtu_dictionary_entity_bundle_info_alter(array &$bundles): void {
  if (isset($bundles['node']['dictionary_word'])) {
    $bundles['node']['dictionary_word']['class'] = DictionaryWord::class;
  }
}
