mukurtu_search.settings:
  type: config_object
  label: 'Mukurtu search settings'
  mapping:
    backend:
      type: string
      label: 'Search backend'
    collapse_multipage_pages:
      type: boolean
      label: 'Show only the first page of multipage items in search results by default'
    collapse_community_records:
      type: boolean
      label: 'Show only original records in search results by default, not community records'
