<?php

/**
 * @file
 * This module provides a consent popup block.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function consent_popup_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.consent_popup':
      $readme = __DIR__ . '/README.md';
      $text = file_get_contents($readme);
      $output = '';

      // If the Markdown module is installed, use it to render the README.
      if ($text && \Drupal::moduleHandler()->moduleExists('markdown') === TRUE) {
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        $output = $filter->process($text, 'en');
      }
      // Else the Markdown module is not installed output the README as text.
      elseif ($text) {
        $output = '<pre>' . $text . '</pre>';
      }
      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function consent_popup_theme() {
  return [
    'consent_popup' => [
      'variables' => [
        'items' => NULL,
      ],
      'template' => 'consent-popup',
    ],
  ];
}
