<?php

/**
 * @file
 * Provides integration with Tagify libraries.
 */

use Drupal\Core\Theme\Icon\IconDefinition;

/**
 * Alter a tagify autocomplete match.
 *
 * @param string|null $label
 *   The matched label. Set to NULL to exclude the match.
 * @param string|null $info_label
 *   The extra information to be shown aside the entity label.
 * @param array $context
 *   An array of context data. The following keys are always available:
 *     - entity: The entity object.
 *     - info_label: The info label, but without token replacement.
 *
 * @throws \GuzzleHttp\Exception\GuzzleException
 * @throws \JsonException
 */
function tagify_icons_tagify_autocomplete_match_alter(?string &$label, ?string &$info_label, array $context): void {
  // Override the info label with svg icon.
  if (str_contains($context['info_label'] ?? '', ':target_id')) {
    // @phpstan-ignore-next-line
    $renderable = IconDefinition::getRenderable($info_label);
    $info_label = \Drupal::service('renderer')->renderInIsolation($renderable);
  }
}
