genpass.settings:
  type: config_object
  label: Generate Password Settings
  mapping:
    genpass_length:
      type: integer
      label: Generated password length
      constraints:
        Range:
          min: 5
          max: 32
    genpass_mode:
      type: integer
      label: User ability to set password during registration
      constraints:
        Range:
          min: 0
          max: 2
        GenpassMode:
          operationMode: 'genpass_mode'
    genpass_admin_mode:
      type: integer
      label: Administrator's ability to set password for edit/create users
      constraints:
        Range:
          min: 1
          max: 2
    genpass_display:
      type: integer
      label: When to display generated password
      constraints:
        Range:
          min: 0
          max: 3
    genpass_override_core:
      type: boolean
      label: Override core DefaultPasswordGenerator
  constraints:
    FullyValidatable: ~

action.configuration.genpass_set_random_password:
  type: action_configuration_default
  label: Set new random password for user(s)
