<?php

/**
 * @file
 * Contains genpass.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\genpass\Hook\FormAdminAlter;
use Drupal\genpass\Hook\FormAlter;
use Drupal\genpass\Hook\Help;
use Drupal\genpass\Hook\UserForms;

/**
 * Implements hook_help().
 */
#[LegacyHook]
function genpass_help($route_name, RouteMatchInterface $route_match) {
  // @todo Remove when minimum version is ^11.1 as it will be called directly.
  return \Drupal::service(Help::class)->help($route_name, $route_match);
}

/**
 * Implements hook_config_schema_info_alter().
 */
#[LegacyHook]
function genpass_config_schema_info_alter(&$definitions) {
  // @todo Remove when minimum version is ^11.1 as it will be called directly.
  \Drupal::service(FormAdminAlter::class)->configSchemaAlter($definitions);
}

/**
 * Implements hook_rebuild().
 */
#[LegacyHook]
function genpass_rebuild() {
  // @todo Remove when minimum version is ^11.1 as it will be called directly.
  return \Drupal::service(FormAlter::class)->buildInfo();
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * User admin settings form at admin/config/people/accounts.
 */
#[LegacyHook]
function genpass_form_user_admin_settings_alter(
  &$form,
  FormStateInterface $form_state,
  $form_id,
) {
  // @todo Remove when minimum version is ^11.1 as it will be called directly.
  \Drupal::service(FormAdminAlter::class)->adminFormAlter(
    $form,
    $form_state,
    $form_id
  );
}

/**
 * Implements hook_form_alter().
 */
#[LegacyHook]
function genpass_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // @todo Remove when minimum version is ^11.1 as it will be called directly.
  \Drupal::service(FormAlter::class)->formAlter(
    $form,
    $form_state,
    $form_id
  );
}

/**
 * Implements hook_genpass_user_forms().
 */
#[LegacyHook]
function genpass_genpass_user_forms(): array {
  // @todo Remove when minimum version is ^11.1 as it will be called directly.
  return \Drupal::service(UserForms::class)->genpassUserForms();
}
