name: Mukurtu CI Tests
on:
  push:
    branches:
      - main
      - develop
jobs:
  testing:
    name: Mukurtu v4 - PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php-versions: ['7.4']
        test-suite: ["kernel"]
        include:
          - php-versions: '7.4'
            test-suite: "kernel"
    services:
      mariadb:
        image: mariadb:10.5
        env:
          MYSQL_USER: db
          MYSQL_PASSWORD: db
          MYSQL_DATABASE: db
          MYSQL_ROOT_PASSWORD: db
        ports:
          - 3306:3306
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: web/profiles/mukurtu-cms

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2

      - name: Setup Mysql client
        run: |
          sudo apt-get update
          sudo apt-get remove -y mysql-client mysql-common
          sudo apt-get install -y mysql-client

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Mukurtu
        run: |
          cp ./web/profiles/mukurtu-cms/phpunit.xml ./web/phpunit.xml
          cp ./web/profiles/mukurtu-cms/mukurtu-gitpod-site.composer.json composer.json
          composer require --dev phpspec/prophecy-phpunit:^2
          composer --no-interaction --no-progress --prefer-dist --optimize-autoloader install

      - name: Mukurtu Tests
        run: |
          ls /home/runner/work/mukurtu-cms/mukurtu-cms
          ls /home/runner/work/mukurtu-cms
          cd /home/runner/work/mukurtu-cms/mukurtu-cms/
          sed -i '/core:.*/d' ./web/modules/contrib/config_sync/tests/modules/config_sync_test/config_sync_test.info.yml || true
          cd ./web
          ../vendor/bin/phpunit --verbose --testsuite "${{ matrix.test-suite }}"
        continue-on-error: false
