name: Mukurtu CI Tests
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  testing:
    name: Mukurtu v4 - PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php-versions: ['8.3']
        test-suite: ["kernel"]
    services:
      mariadb:
        image: mariadb:10.5
        env:
          MYSQL_USER: db
          MYSQL_PASSWORD: db
          MYSQL_DATABASE: db
          MYSQL_ROOT_PASSWORD: db
        ports:
          - 3306:3306
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2

      - name: Setup Mysql client
        run: |
          sudo apt-get update --allow-releaseinfo-change
          sudo apt-get remove -y mysql-client mysql-common
          sudo apt-get install -y mysql-client

      - name: Get composer cache directory
        id: composercache
        run: echo "COMPCACHE=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: $COMPCACHE
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      # Install the mukurtu-template into the root, then remove the packaged
      # version of mukurtu-cms, which will be replaced by the git checkout.
      - name: Install Mukurtu Template
        run: |
          composer create mukurtu/mukurtu-template:dev-main . --no-install --no-interaction
          rm web/profiles/mukurtu -rf

      # Usually checkout is the first action, but we set up the mukurtu-template
      # first, then put the checkout inside of it.
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: web/profiles/mukurtu

      - name: Install Mukurtu
        run: |
          composer config repositories.local-dev path web/profiles/mukurtu
          composer install --no-interaction --optimize-autoloader
          cp ./web/profiles/mukurtu/phpunit.xml ./phpunit.xml

      - name: Mukurtu Tests
        run: |
          ./vendor/bin/phpunit --verbose --testsuite "${{ matrix.test-suite }}"
        continue-on-error: false
