name: "Tugboat Playwright Tests"

on:
  # Run on pull requests against the main branch, to match Tugboat builds.
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  wait-for-tugboat:
    runs-on: ubuntu-latest
    outputs:
      preview_url: ${{ steps.wait-for-preview.outputs.preview_url }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Wait for Tugboat Preview
        id: wait-for-preview
        run: |
          # Define the maximum wait time (5 minutes).
          MAX_WAIT=300
          INTERVAL=30
          ELAPSED=0
          while [ $ELAPSED -lt $MAX_WAIT ]; do
            PREVIEW_URL=$(gh api repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments | jq -r '.[].body' | grep -Po 'https://(?!www\.)[a-zA-Z0-9.-]+\.tugboatqa.com' | head -n 1 || true)
            if [[ ! -z "$PREVIEW_URL" ]]; then
              echo "Preview is ready: $PREVIEW_URL"
              echo "preview_url=$PREVIEW_URL" >> "$GITHUB_OUTPUT"
              exit 0
            fi
            echo "Waiting for Tugboat preview..."
            sleep $INTERVAL
            ELAPSED=$((ELAPSED + INTERVAL))
          done
          echo "Tugboat preview did not become ready in time."
          exit 1
        env:
          # Secret configured on the Mukurtu-CMS repository.
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  playwright-tests:
    needs: wait-for-tugboat
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        working-directory: tests/playwright
        run: npm ci

      - name: Install Playwright Browsers
        working-directory: tests/playwright
        run: npx playwright install

      - name: Run Playwright Tests
        working-directory: tests/playwright
        run: npx playwright test
        # Note this needs process.env.PLAYWRIGHT_BASE_URL to be evaluated in
        # as the baseURL in playwright.config.ts.
        env:
          PLAYWRIGHT_BASE_URL: ${{ needs.wait-for-tugboat.outputs.preview_url }}
